// Cross-platform spawn/kill for the Studio server subprocess.
// Pure argv construction is exported separately so unit tests can
// assert the exact command line per platform without spawning.
import { type ChildProcess, execFile, spawn } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

export interface SpawnSpec {
  command: string;
  args: string[];
}

/**
 * Build the argv for an extension-owned Studio server.
 * Runs `python -m amx.web._studio_subprocess` directly — the actual
 * server entry, parent-agnostic, no browser-open side effects.
 */
export function buildServerSpawnSpec(options: {
  pythonPath: string;
  port: number;
  token: string;
  configPath?: string;
  /**
   * Servers older than the embedded-host release reject the
   * --embedded/--owner flags outright (argparse exits 2), so the
   * caller gates them on the resolved AMX version. Without them the
   * server still runs — trees and editor features work, only the
   * iframe panels are blocked by the strict framing headers.
   */
  supportsEmbedded: boolean;
}): SpawnSpec {
  const args = [
    "-m",
    "amx.web._studio_subprocess",
    "--port",
    String(options.port),
    "--token",
    options.token,
  ];
  if (options.supportsEmbedded) {
    args.push("--embedded", "--owner", "vscode");
  }
  if (options.configPath) {
    args.push("--config-path", options.configPath);
  }
  return { command: options.pythonPath, args };
}

/**
 * Build the argv for spawning through the `amx` CLI binary (pipx
 * installs where no importable interpreter is reachable). The token
 * is generated by the launcher and recovered from the discovery file
 * the server writes.
 *
 * The AMX CLI blocks direct subcommands from a terminal (interactive
 * REPL only); internally-dispatched invocations are whitelisted via
 * AMX_SESSION_CHILD=1 — the same channel the REPL itself uses — so
 * every CLI-kind spawn and probe must carry that env marker.
 */
export function buildCliSpawnSpec(options: { amxCliPath: string; port: number }): SpawnSpec {
  return {
    command: options.amxCliPath,
    args: ["studio", "--no-open", "--embedded", "--port", String(options.port)],
  };
}

/** Environment for machine-dispatched `amx` CLI invocations. */
export function cliDispatchEnv(): NodeJS.ProcessEnv {
  return { ...process.env, AMX_SESSION_CHILD: "1" };
}

/**
 * Detect whether the installed AMX supports the embedded host mode
 * (and the discovery file that ships with it) by probing the help
 * text for the --embedded flag. Works for both runtime kinds:
 * `python -m amx.web._studio_subprocess --help` and
 * `amx studio --help` both list the flag from the release that
 * introduced it; older versions simply don't mention it.
 */
export async function probeEmbeddedSupport(
  runtime: { kind: "python"; pythonPath: string } | { kind: "cli"; amxCliPath: string },
): Promise<boolean> {
  try {
    const { command, args } =
      runtime.kind === "python"
        ? { command: runtime.pythonPath, args: ["-m", "amx.web._studio_subprocess", "--help"] }
        : { command: runtime.amxCliPath, args: ["studio", "--help"] };
    const { stdout, stderr } = await execFileAsync(command, args, {
      timeout: 30_000,
      env: cliDispatchEnv(),
    });
    return (stdout + stderr).includes("--embedded");
  } catch {
    return false;
  }
}

export function spawnServer(spec: SpawnSpec): ChildProcess {
  return spawn(spec.command, spec.args, {
    stdio: ["ignore", "pipe", "pipe"],
    detached: false,
    windowsHide: true,
    env: cliDispatchEnv(),
  });
}

/**
 * Stop an owned server, escalating: polite signal first, then a hard
 * kill after `graceMs`. On Windows `SIGINT` is not deliverable to a
 * detached-stdin child, so go through taskkill with /T to take the
 * process tree down.
 */
/** Whether a process with this pid currently exists (signal 0 probe). */
export function isPidAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

/**
 * Stop a server by raw pid — used to reap an owned server left over
 * from a previous extension host (deactivate cannot await the kill,
 * so reconciliation happens on the next activation). Unlike
 * killServer there is no ChildProcess to await, so liveness is
 * polled between escalation steps.
 */
export async function killPid(pid: number, graceMs = 2000): Promise<void> {
  if (!isPidAlive(pid)) return;
  if (process.platform === "win32") {
    try {
      await execFileAsync("taskkill", ["/pid", String(pid), "/T", "/F"]);
    } catch {
      /* best effort — the process may have exited already */
    }
    return;
  }
  const signalAndWait = async (signal: NodeJS.Signals): Promise<boolean> => {
    try {
      process.kill(pid, signal);
    } catch {
      return true; // already gone
    }
    const deadline = Date.now() + graceMs;
    while (Date.now() < deadline) {
      if (!isPidAlive(pid)) return true;
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
    return !isPidAlive(pid);
  };
  if (await signalAndWait("SIGINT")) return;
  if (await signalAndWait("SIGTERM")) return;
  try {
    process.kill(pid, "SIGKILL");
  } catch {
    /* already gone */
  }
}

export async function killServer(proc: ChildProcess, graceMs = 2000): Promise<void> {
  if (proc.exitCode !== null || proc.signalCode !== null) return;
  const exited = new Promise<void>((resolve) => {
    proc.once("exit", () => resolve());
  });
  if (process.platform === "win32") {
    proc.kill();
    const fallback = setTimeout(() => {
      if (proc.pid !== undefined && proc.exitCode === null) {
        execFile("taskkill", ["/pid", String(proc.pid), "/T", "/F"], () => {
          /* best effort */
        });
      }
    }, graceMs);
    await exited;
    clearTimeout(fallback);
    return;
  }
  proc.kill("SIGINT");
  const escalate = setTimeout(() => {
    if (proc.exitCode === null) proc.kill("SIGTERM");
  }, graceMs);
  const lastResort = setTimeout(() => {
    if (proc.exitCode === null) proc.kill("SIGKILL");
  }, graceMs * 2);
  await exited;
  clearTimeout(escalate);
  clearTimeout(lastResort);
}
